In [2]:
import pandas as pd
import numpy as np

In [17]:
# Load dataframe with breast cancer data

columns = list(np.arange(0, 32, 1))
df = pd.read_csv('wdbc.data.csv', names=columns)
df

0  1      2      3       4       5        6        7        8   \
0      842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [18]:
# Encode class column as -1 / 1 to fit SVM algorithm
# -1 is malignant and 1 is benign

df[1] = np.where(df[1] == "M", -1, 1)
df

0   1      2      3       4       5        6        7        8   \
0      842302  -1  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  -1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  -1  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  -1  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  -1  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ...  ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  -1  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  -1  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  -1  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  -1  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751   1   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [49]:
# Create 569 x 1 class label array

Y = df[1].to_numpy()
Y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1,  1,
        1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,
        1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1,
       -1, -1, -1,  1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1,
        1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1, -1, -1,
        1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1,
        1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1,  1, -1,
        1,  1,  1, -1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1, -1,
        1, -1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1,  1,
        1,  1, -1,  1,  1

In [69]:
# Create 569 x 30 covariate matrix
# Each column represents one observation with 30 covariates

X = df.drop(columns=[0, 1]).to_numpy().T
X

array([[1.799e+01, 2.057e+01, 1.969e+01, ..., 1.660e+01, 2.060e+01,
        7.760e+00],
       [1.038e+01, 1.777e+01, 2.125e+01, ..., 2.808e+01, 2.933e+01,
        2.454e+01],
       [1.228e+02, 1.329e+02, 1.300e+02, ..., 1.083e+02, 1.401e+02,
        4.792e+01],
       ...,
       [2.654e-01, 1.860e-01, 2.430e-01, ..., 1.418e-01, 2.650e-01,
        0.000e+00],
       [4.601e-01, 2.750e-01, 3.613e-01, ..., 2.218e-01, 4.087e-01,
        2.871e-01],
       [1.189e-01, 8.902e-02, 8.758e-02, ..., 7.820e-02, 1.240e-01,
        7.039e-02]])

In [62]:
# Create 30 x 1 weight vector with initial weights
# Also create 569 x 1 intercept / bias vector with initial value

W = np.ones(X.shape[1])
b = np.ones(X.shape[0])

In [57]:
# Transform class label vector into triangular matrix with labels on diagonal

Y_triang = np.zeros((X.shape[0], X.shape[0]))
np.fill_diagonal(Y_triang, Y)
Y_triang

array([[-1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., -1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., -1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., -1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., -1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [89]:
# Initialize 569 x 1 error / residual vector, and penalty term C

epsilon_vec = np.ones(X.shape[0])
C = 10000

In [83]:
# Function to be minimized

def function_to_minimize(W, C, epsilon_vec):
    
    # Calculate value of function for current weights and deviations
    function_val = 0.5 * (W.T @ W) + C * np.sum(epsilon_vec)
    
    return function_val

In [84]:
function_to_minimize(W, C, epsilon_vec)

60014.7303706

In [91]:
def constraint_function(W, X, b, Y_triang):
        
    # Predicted value for each x_i with current weights, times actual class label
    pred_actual_val = (W @ X + b) @ Y_triang
    
    # Epsilon value for each x_i on the wrong side of support vector
    epsilon_vec = np.where(pred_actual_val < 1, 1 - pred_actual_val, 0)
    
    return epsilon_vec

In [92]:
epsilon_vec = constraint_function(W, X, b, Y_triang)

In [81]:
pred_actual_val

array([-3567.178472 , -3741.923467 , -3388.392551 , -1241.001848 ,
       -3337.684215 , -1506.545302 , -3068.937363 , -1815.437947 ,
       -1565.89724  , -1494.434399 , -2313.544951 , -2464.194955 ,
       -2969.470789 , -2002.877251 , -1588.871452 , -1960.529563 ,
       -2178.458183 , -2511.380978 , -4198.341491 ,  1556.287762 ,
        1415.698602 ,   783.237384 , -2033.399403 , -4556.225505 ,
       -3615.933599 , -2843.915363 , -1876.952953 , -2951.240347 ,
       -2403.10621  , -2574.218189 , -3260.945648 , -1652.169988 ,
       -2663.693942 , -3441.884584 , -2431.428989 , -2482.654891 ,
       -1756.97975  ,  1324.138428 , -1788.423189 , -1595.431304 ,
       -1646.429037 , -1148.296884 , -3282.836784 , -1769.981329 ,
       -1564.014513 , -3078.930679 ,   621.671134 , -1589.177935 ,
        1286.34489  ,  1554.545131 ,  1208.909859 ,  1498.931274 ,
        1210.821755 , -2800.219737 , -2080.454916 ,  1165.161936 ,
       -3797.265666 , -1986.328637 ,  1432.052847 ,   671.4176

In [82]:
epsilon_vec

array([3568.178472, 3742.923467, 3389.392551, 1242.001848, 3338.684215,
       1507.545302, 3069.937363, 1816.437947, 1566.89724 , 1495.434399,
       2314.544951, 2465.194955, 2970.470789, 2003.877251, 1589.871452,
       1961.529563, 2179.458183, 2512.380978, 4199.341491,    0.      ,
          0.      ,    0.      , 2034.399403, 4557.225505, 3616.933599,
       2844.915363, 1877.952953, 2952.240347, 2404.10621 , 2575.218189,
       3261.945648, 1653.169988, 2664.693942, 3442.884584, 2432.428989,
       2483.654891, 1757.97975 ,    0.      , 1789.423189, 1596.431304,
       1647.429037, 1149.296884, 3283.836784, 1770.981329, 1565.014513,
       3079.930679,    0.      , 1590.177935,    0.      ,    0.      ,
          0.      ,    0.      ,    0.      , 2801.219737, 2081.454916,
          0.      , 3798.265666, 1987.328637,    0.      ,    0.      ,
          0.      ,    0.      , 1977.5457  ,    0.      , 1714.240272,
       1938.371057,    0.      ,    0.      ,    0.      ,    0.

In [85]:
from scipy import optimize

In [95]:
epsilon_cons = ({"type": "ineq", "fun": constraint_function(W, X, b, Y_triang)})

optim = optimize.minimize(fun=function_to_minimize, x0=W, method="SLSQP", constraints=epsilon_cons)

TypeError: constraint_function() missing 1 required positional argument: 'Y_triang'

In [ ]:
"""Perceptron from ITDS, For inspiration

def perceptron(X_in,labels,max_iter=10000):
    '''Runs the perceptron algorithm on X_in, labels, and does a maximum of max_iter iterations'''
    #n_points = X_in.shape[0]
    n_steps = 2000
    X = np.c_[X_in, np.ones(X_in.shape[0])]
    n_points = X.shape[0]
    k ,j = 0, 0
    W = np.array([0,0,0])
    while ((k < n_steps) and (j < max_iter)):
        i = j % n_points
        j+=1

        if (X[i, :]@W * labels[i] <= 0):
            W = W + X[i,:]*labels[i]
            #P+=points(X[i,:2],color=’yellow’)
            k+=1
    print(W)
    W = W.reshape(3, 1)
    print(j)
    print(W.shape)
    w = W
    # Dont forget the addition of the extra dimension to encode the
    # bias in the perceptron, i.e. adding the extra dimension with value 1
    
    return w #Make sure that w has the shape described in the problem
    
"""